### ISSUE TITLE
При успешном пополнении счета, баланс не увеличивается

### ISSUE THREAD

**Issue by Dimonstratos** [VSmirnovaV/teamWork#10]
# Описание
При пополнении, баланс должен увеличится на сумму пополнения.

# Локация дефекта
https://github.com/VSmirnovaV/teamWork/blob/6d289419bcff935106073dc16bba8aeca4943ed6/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L33

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/VSmirnovaV/teamWork/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
1. Выбрать тест "shouldAddLessThanMaxBalance"
1. Вставить значение переменной InitialBalance 2000
1. Вставить значение переменной minBalance 1000
1. Вставить значение переменной maxBalance 10000
1. Вставить значение переменной rate 5
1. Ввести сумму пополнения account.add(3_000)
1. Запустить тест
1. Посмотреть результат в консоли

Ожидаемый результат: баланс счета равен 5000
Фактический результат: баланс счета равен 3000

# Тест
https://github.com/VSmirnovaV/teamWork/blob/47e5d6c3248b0a5ed1d4928e6592d76c917cb500/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L10

# Скриншот
![shouldAddLessThanMaxBalance](https://github.com/VSmirnovaV/teamWork/assets/130654761/6899c880-28d8-4bdc-b621-a848723f70f1)

# Окружение
* **Операционная система:** Windows 10 LTSC
* **IDEA:** IntelliJ IDEA 2023.1.1 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by VSmirnovaV** [comment]
# **Исправлено**

# **Тест**
https://github.com/VSmirnovaV/teamWork/blob/47e5d6c3248b0a5ed1d4928e6592d76c917cb500/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L10
