### ISSUE TITLE
Не уменьшается счет при покупке

### ISSUE THREAD

**Issue by Dimonstratos** [VSmirnovaV/teamWork#11]
# Описание
При покупке счет не уменьшается после достижения минимального значения

# Локация дефекта
https://github.com/VSmirnovaV/teamWork/blob/6d289419bcff935106073dc16bba8aeca4943ed6/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L21

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/VSmirnovaV/teamWork/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
1. Выбрать тест "testPayMinBalance"
1. Вставить значение переменной InitialBalance 2000
1. Вставить значение переменной minBalance 1000
1. Вставить значение переменной maxBalance 10000
1. Вставить значение переменной rate 5
1. Ввести сумму пополнения account.pay(1_000)
1. Запустить тест
1. Посмотреть результат в консоли

Ожидаемый результат: метод pay возвращает true = 1000
Фактический результат: метод pay возвращает false

# Тест
https://github.com/VSmirnovaV/teamWork/blob/47e5d6c3248b0a5ed1d4928e6592d76c917cb500/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L285

# Скриншот
![testPayMinBalance](https://github.com/VSmirnovaV/teamWork/assets/130654761/4e416085-98f1-496e-8bf7-019a0f407945)

# Окружение
* **Операционная система:** Windows 10 LTSC
* **IDEA:** IntelliJ IDEA 2023.1.1 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by VSmirnovaV** [comment]
# **Исправлено**

# **Тест**
https://github.com/VSmirnovaV/teamWork/blob/47e5d6c3248b0a5ed1d4928e6592d76c917cb500/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L285
