### ISSUE TITLE
Не выкидывается значение IllegalArgumentException при установке отрицательного начального баланса

### ISSUE THREAD

**Issue by Dimonstratos** [VSmirnovaV/teamWork#12]
# **Описание**
При установке начального баланса( `InitialBalance`) не выкидывается исключение вида IllegalArgumentException

# **Локация дефекта**
https://github.com/VSmirnovaV/teamWork/blob/47e5d6c3248b0a5ed1d4928e6592d76c917cb500/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# **Шаги воспроизведения**
1. Открыть [код программы](https://github.com/VSmirnovaV/teamWork/blob/6d289419bcff935106073dc16bba8aeca4943ed6/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L6C5-L6C5) в IDEA
2. Выставить значение переменной `InitialBalance` = -1000
3. Запустить программу
4. Посмотреть на вывод в консоли

***Ожидаемый результат:*** В консоли выводится сообщение "Начальный баланс не может быть отрицательным, а у вас" + `initialBalance`
***Фактический результат:*** Переменная `InitialBalance` принимает значение - 1000

# **Тест**
https://github.com/VSmirnovaV/teamWork/blob/47e5d6c3248b0a5ed1d4928e6592d76c917cb500/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L38

# Cкриншот
![image](https://github.com/VSmirnovaV/teamWork/assets/131758107/130f8f2d-1adf-45de-815c-f8ef0612ebd8)

# Окружение
* **Операционная система:**  Windows 10, Версия 21H1
* **IDE:** IntelliJ IDEA 2023.1.1 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by VSmirnovaV** [comment]
# **Исправлено**

# **Тест**
https://github.com/VSmirnovaV/teamWork/blob/47e5d6c3248b0a5ed1d4928e6592d76c917cb500/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L38
