### ISSUE TITLE
При покупке списывается сумма, превышающая баланс. 

### ISSUE THREAD

**Issue by Dimonstratos** [VSmirnovaV/teamWork#13]
# Описание
При списании средств превышающих сумму баланса, счет принимает отрицательное значение.
  

# Локация дефекта

https://github.com/VSmirnovaV/teamWork/blob/6d289419bcff935106073dc16bba8aeca4943ed6/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L21

# Шаги воспроизведения
1. Открыть код программы в IDEA
1. Выбрать тест "testPayNegative"
1. Вставить значение переменной InitialBalance 2000
1. Вставить значение переменной minBalance 1000
1. Вставить значение переменной maxBalance 10000
1. Вставить значение переменной rate 5
1. Ввести сумму пополнения account.pay(3_000)
1. Запустить тест
1. Посмотреть результат в консоли

Ожидаемый результат: Баланс не может быть отрицательным
Фактический результат: тест проходит.

# Тест
https://github.com/VSmirnovaV/teamWork/blob/47e5d6c3248b0a5ed1d4928e6592d76c917cb500/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L300

# Скриншот

![testPayNegative](https://github.com/VSmirnovaV/teamWork/assets/130654761/7d8e3bc4-b71f-4480-99b3-1533a36a3f73)

# Окружение
* **Операционная система:** Windows 10 LTSC
* **IDEA:** IntelliJ IDEA 2023.1.1 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by VSmirnovaV** [comment]
# **Исправлено**

# **Тест**
https://github.com/VSmirnovaV/teamWork/blob/47e5d6c3248b0a5ed1d4928e6592d76c917cb500/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L300
