### ISSUE TITLE
Не пополняется счет при максимальном значении

### ISSUE THREAD

**Issue by Dimonstratos** [VSmirnovaV/teamWork#2]
# Описание
При пополнении карты, баланс должен увеличиться на указанную сумму.

# Локация дефекта
https://github.com/VSmirnovaV/teamWork/blob/6d289419bcff935106073dc16bba8aeca4943ed6/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L32

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/VSmirnovaV/teamWork/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
1. Выбрать тест "testMaxBalance1"
1. Вставить значение переменной InitialBalance 2000
1. Вставить значение переменной minBalance 1000
1. Вставить значение переменной maxBalance 10000
1. Вставить значение переменной rate 5
1. Ввести сумму пополнения account.add(8_000)
1. Запустить тест
1. Посмотреть результат в консоли

Ожидаемый результат: баланс счета равен 10000
Фактический результат: баланс счета равен 2000. пополнение не происходит.

# Тест
https://github.com/VSmirnovaV/teamWork/blob/47e5d6c3248b0a5ed1d4928e6592d76c917cb500/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L138

# Скриншот
![testMaxBalance1](https://github.com/VSmirnovaV/teamWork/assets/130654761/731fc6b5-4d91-4c47-8873-2025179ca514)

# Окружение
* **Операционная система:** Windows 10 LTSC
* **IDEA:** IntelliJ IDEA 2023.1.1 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by VSmirnovaV** [comment]
# **Исправлено**

# **Тест**
https://github.com/VSmirnovaV/teamWork/blob/47e5d6c3248b0a5ed1d4928e6592d76c917cb500/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L138
